# Generated by Django 6.0.4 on 2026-08-26 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('student_id', models.CharField(db_index=True, help_text='Unique Student Identification Number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('national_id_number', models.CharField(blank=True, help_text='National ID / Birth Certificate No.', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/%Y/')),
                ('admission_date', models.DateField()),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste_category', models.CharField(blank=True, default='General', max_length=50)),
                ('nationality', models.CharField(default='United States', max_length=50)),
                ('residential_address', models.TextField()),
                ('permanent_address', models.TextField(blank=True)),
                ('city', models.CharField(default='Metro City', max_length=100)),
                ('state', models.CharField(default='State', max_length=100)),
                ('postal_code', models.CharField(default='100001', max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=50)),
                ('emergency_contact_relation', models.CharField(help_text='e.g. Father, Mother, Uncle', max_length=50)),
                ('previous_school_name', models.CharField(blank=True, max_length=200)),
                ('previous_school_tc_number', models.CharField(blank=True, help_text='Transfer Certificate No.', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Enrolled'), ('GRADUATED', 'Graduated / Alumni'), ('TRANSFERRED', 'Transferred Out'), ('SUSPENDED', 'Suspended'), ('DROPOUT', 'Withdrawn / Dropped Out')], db_index=True, default='ACTIVE', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('roll_number', models.PositiveIntegerField(help_text='Roll number within section for the academic year')),
                ('enrollment_date', models.DateField()),
                ('is_current', models.BooleanField(default=True, help_text='Indicates active enrollment for current session')),
                ('promotion_status', models.CharField(choices=[('ENROLLED', 'Currently Enrolled'), ('PROMOTED', 'Promoted to Next Grade'), ('RETAINED', 'Retained / Repeated'), ('DETACHED', 'Detached / Completed')], default='ENROLLED', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['section', 'roll_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('allergies_summary', models.TextField(blank=True, help_text='Food, drug, or environmental allergies')),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g. Asthma, Diabetes, Epilepsy')),
                ('medications', models.TextField(blank=True, help_text='Regular prescriptions or emergency meds')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Vegetarian, Halal, Nut-free, etc.')),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('doctor_phone', models.CharField(blank=True, max_length=50)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Health Record',
                'verbose_name_plural': 'Student Health Records',
            },
        ),
        migrations.CreateModel(
            name='StudentMedicalIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('incident_date', models.DateTimeField()),
                ('title', models.CharField(help_text='e.g. Sports Injury, Fever, Allergic Reaction', max_length=200)),
                ('description', models.TextField()),
                ('treatment_given', models.TextField()),
                ('referred_to_hospital', models.BooleanField(default=False)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_medical_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_incidents', to='students.student')),
            ],
            options={
                'verbose_name': 'Medical Incident',
                'verbose_name_plural': 'Medical Incidents',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number', 'status'], name='students_st_admissi_e88f69_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_st_first_n_e9466d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['academic_year', 'section', 'is_current'], name='students_st_academi_126930_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'is_current'], name='students_st_student_a25061_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('academic_year', 'section', 'roll_number'), ('student', 'academic_year')},
        ),
    ]
