# Generated by Django 6.0.4 on 2026-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, default='Metro City', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='United States', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=models.CharField(blank=True, default='100001', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, default='State', max_length=100),
        ),
    ]
