# Generated by Django 6.0.4 on 2026-08-26 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Apex International Academy', max_length=200)),
                ('code', models.CharField(default='APEX-SMS', help_text='Unique school registration code', max_length=50)),
                ('tagline', models.CharField(blank=True, default='Excellence in Education and Character', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school/branding/')),
                ('address', models.TextField(blank=True, default='123 Academy Boulevard, Knowledge City')),
                ('city', models.CharField(blank=True, default='Metro City', max_length=100)),
                ('state', models.CharField(blank=True, default='State', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='100001', max_length=20)),
                ('country', models.CharField(blank=True, default='United States', max_length=100)),
                ('phone', models.CharField(blank=True, default='+1 (555) 019-2834', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@apexacademy.edu', max_length=254)),
                ('website', models.URLField(blank=True, default='https://apexacademy.edu')),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('date_format', models.CharField(choices=[('d M Y', '26 Aug 2026 (d M Y)'), ('Y-m-d', '2026-08-26 (Y-m-d)'), ('d/m/Y', '26/08/2026 (d/m/Y)'), ('m/d/Y', '08/26/2026 (m/d/Y)')], default='d M Y', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('attendance_threshold_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum required attendance percentage for exam eligibility', max_digits=5)),
                ('enable_student_login', models.BooleanField(default=True)),
                ('enable_parent_login', models.BooleanField(default=True)),
                ('enable_online_admissions', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('EXPORT', 'Data Export'), ('BULK_ACTION', 'Bulk Action'), ('STATUS_CHANGE', 'Status Change')], db_index=True, max_length=20)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'timestamp'], name='core_auditl_module_3b671b_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx')],
            },
        ),
    ]
