# Generated by Django 6.0.4 on 2026-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsetting',
            name='address',
            field=models.TextField(blank=True, default='Sector 14, Urban Estate, Rohini'),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='city',
            field=models.CharField(blank=True, default='New Delhi', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='code',
            field=models.CharField(default='HPS-DELHI', help_text='Unique school registration code', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='email',
            field=models.EmailField(blank=True, default='admissions@horizonpublicschool.edu.in', max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='name',
            field=models.CharField(default='Horizon Public School', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='phone',
            field=models.CharField(blank=True, default='+91 (011) 2748-9012 / +91 98765 43210', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='postal_code',
            field=models.CharField(blank=True, default='110085', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='state',
            field=models.CharField(blank=True, default='Delhi (NCT)', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='tagline',
            field=models.CharField(blank=True, default='Affiliated to CBSE, New Delhi (Affiliation No. 2130894)', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='website',
            field=models.URLField(blank=True, default='https://horizonpublicschool.edu.in'),
        ),
    ]
