# Generated by Django 6.0.4 on 2026-08-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schoolsetting_address_alter_schoolsetting_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='affiliation_number',
            field=models.CharField(blank=True, default='2130894', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='affiliation_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='assembly_duration_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='board_name',
            field=models.CharField(choices=[('CBSE', 'Central Board of Secondary Education (CBSE)'), ('ICSE', 'Council for the Indian School Certificate Examinations (CISCE / ICSE)'), ('STATE', 'State Board of School Education'), ('IB', 'International Baccalaureate (IB)'), ('CAMBRIDGE', 'Cambridge International (CAIE)')], default='CBSE', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='consecutive_absence_warning_days',
            field=models.PositiveIntegerField(default=3, help_text='Days of unexcused absence before auto-generating parent warning notice'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='discipline_policy',
            field=models.TextField(blank=True, default='Students must uphold the highest standards of integrity, punctuality, and mutual respect. Bullying, ragging, vandalism, or possession of unauthorized items is strictly prohibited under institutional POCSO & CBSE bylaws.'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='enable_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='enable_ip_whitelisting',
            field=models.BooleanField(default=False, help_text='Restrict POS & sensitive operations to authorized campus IPs'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='enable_sms_dlt_gateway',
            field=models.BooleanField(default=True, help_text='Enable Indian TRAI/DLT compliant SMS gateway'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='enable_staff_2fa',
            field=models.BooleanField(default=False, help_text='Require 2FA OTP for Admins and Finance Officers'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='enable_whatsapp_notifications',
            field=models.BooleanField(default=True, help_text='Send real-time fee receipts & absent alerts via WhatsApp'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='exam_incharge_signature',
            field=models.ImageField(blank=True, null=True, upload_to='school/signatures/'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='fee_due_day_of_month',
            field=models.PositiveIntegerField(default=10, help_text='Day of month (1-31) after which late fine starts calculating'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='fee_receipt_format',
            field=models.CharField(choices=[('3_COPY_STRIP', '3-Copy Bank/School/Student Strip (CBSE Standard)'), ('A4_DUAL', 'A4 Dual Copy Format'), ('THERMAL_POS', '80mm Thermal POS Receipt')], default='3_COPY_STRIP', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='grievance_escalation_matrix',
            field=models.TextField(blank=True, default='Level 1: Class Teacher -> Level 2: Section Coordinator -> Level 3: Vice Principal -> Level 4: Principal / Management'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='late_coming_grace_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Grace period (in minutes) after morning assembly bell'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Per-day fine levied after fee submission due date', max_digits=8),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='late_marks_for_half_day',
            field=models.PositiveIntegerField(default=3, help_text='Number of late arrival marks that convert to 1 half-day leave'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='medical_leave_cert_threshold_days',
            field=models.PositiveIntegerField(default=3, help_text='Leaves exceeding these consecutive days require registered MBBS doctor certificate'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='mobile_device_policy',
            field=models.CharField(choices=[('PROHIBITED', 'Strictly Prohibited on Campus'), ('LOCKER_DEPOSITED', 'Allowed with Morning Locker Deposit'), ('CLASSROOM_PERMITTED', 'Permitted for Digital Smart Learning')], default='LOCKER_DEPOSITED', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='operating_shift',
            field=models.CharField(choices=[('SINGLE', 'Single Shift (Morning Standard)'), ('DOUBLE_MORNING', 'Double Shift - Morning Wing'), ('DOUBLE_AFTERNOON', 'Double Shift - Afternoon Wing')], default='SINGLE', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='passing_marks_percentage',
            field=models.DecimalField(decimal_places=2, default=33.0, help_text='Minimum passing percentage per subject (CBSE Standard)', max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='period_duration_minutes',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='school/signatures/'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='ptm_visiting_hours',
            field=models.CharField(blank=True, default='2nd Saturday: 09:00 AM - 01:00 PM | Weekdays by prior appointment: 02:30 PM - 03:30 PM', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='recess_duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='report_card_layout',
            field=models.CharField(choices=[('CBSE_2TERM', 'CBSE 2-Term Standard CCE Format'), ('NEP_HPC', 'NEP 2020 Holistic Progress Card (HPC)')], default='CBSE_2TERM', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='rte_quota_seats_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Right to Education (RTE 25%) mandatory seat quota', max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='school_board_code',
            field=models.CharField(blank=True, default='08124', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='school_end_time',
            field=models.TimeField(default='14:15:00'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='school_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='school/stamps/'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='school_start_time',
            field=models.TimeField(default='07:45:00'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Idle session timeout before automatic logout'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='sibling_concession_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Standard concession percentage for 2nd/3rd sibling', max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='sms_sender_id',
            field=models.CharField(blank=True, default='HRZNSC', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='trust_registration_no',
            field=models.CharField(blank=True, default='REG/DEL/2012/9842', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='trust_society_name',
            field=models.CharField(blank=True, default='Horizon Educational & Charitable Trust', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='uniform_policy',
            field=models.TextField(blank=True, default='Summer: Monday to Friday standard blue crest uniform with black polished shoes. Winter: Navy blazer with school tie and pullover. School ID Card Badge is mandatory at all times.'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='whatsapp_api_provider',
            field=models.CharField(choices=[('OFFICIAL_CLOUD', 'Official Meta WhatsApp Cloud API'), ('TWILIO', 'Twilio WhatsApp Gateway'), ('AISENSY', 'AiSensy / Gallabox Indian Partner API')], default='OFFICIAL_CLOUD', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='whitelisted_ips',
            field=models.TextField(blank=True, default='127.0.0.1, 192.168.1.0/24'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='working_days_per_week',
            field=models.PositiveIntegerField(choices=[(5, '5-Day Week (Monday to Friday)'), (6, '6-Day Week (Mon-Sat with Alternate Saturday Off)')], default=6),
        ),
    ]
