# Generated by Django 6.0.4 on 2026-08-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolsetting_affiliation_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.TextField(blank=True, help_text='Cryptographic license key string issued by developer')),
                ('license_type', models.CharField(choices=[('TRIAL', '7-Day Trial Mode'), ('STANDARD', 'Standard Commercial (1-Year)'), ('PRO', 'Professional Commercial'), ('ENTERPRISE', 'Enterprise Permanent Lifetime'), ('EXTENDED_TRIAL', 'Extended Evaluation Trial')], default='TRIAL', max_length=50)),
                ('status', models.CharField(choices=[('TRIAL_ACTIVE', '7-Day Trial Active'), ('ACTIVE', 'Commercial License Active'), ('TRIAL_EXPIRED', '7-Day Trial Expired'), ('EXPIRED', 'Commercial License Expired'), ('INVALID', 'Invalid / Tampered License'), ('REVOKED', 'License Revoked')], default='TRIAL_ACTIVE', max_length=50)),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Null indicates permanent lifetime license', null=True)),
                ('licensed_to_name', models.CharField(blank=True, default='Horizon Public School', max_length=255)),
                ('licensed_to_code', models.CharField(blank=True, default='HPS-DELHI', max_length=100)),
                ('installation_id', models.CharField(help_text='Unique hardware/installation node identifier', max_length=100, unique=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
                ('meta_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
