# Generated by Django 6.0.4 on 2026-08-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_softwarelicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedLicenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('plan_type', models.CharField(max_length=50)),
                ('licensed_to_code', models.CharField(max_length=100)),
                ('licensed_to_name', models.CharField(max_length=255)),
                ('issued_date', models.CharField(max_length=30)),
                ('expires_str', models.CharField(max_length=30)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Consumed License Token',
                'verbose_name_plural': 'Consumed License Tokens',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='consumed_nonces',
            field=models.JSONField(blank=True, default=list, help_text='Anti-replay ledger of consumed key nonces'),
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='last_system_time',
            field=models.DateTimeField(blank=True, help_text='Protects against clock rollback tampering', null=True),
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='trial_consumed',
            field=models.BooleanField(default=False, help_text='Prevents trial restart after expiration'),
        ),
    ]
