# Generated by Django 6.0.4 on 2026-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictestimonial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
