# Generated by Django 6.0.4 on 2026-08-28 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft In Progress'), ('GENERATED', 'Generated & Verified'), ('APPROVED', 'Approved by Principal'), ('PAID', 'Disbursed & Completed')], default='DRAFT', max_length=20)),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='academics.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('academic_year', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('3500.00'), max_digits=12)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='HRA Allowance', max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Travel/Conveyance Allowance', max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Medical Support Allowance', max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Special/Academic Incentive', max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Income Tax / TDS', max_digits=10)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='PF / Retirement Contribution', max_digits=10)),
                ('insurance_deduction', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Health/Life Insurance Premium', max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Miscellaneous Deductions', max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
            },
        ),
        migrations.CreateModel(
            name='StaffSalarySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('slip_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance_hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allowance_transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allowance_medical', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allowance_special', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('incentives_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_pf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_leave_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_other', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Direct Bank Deposit / Wire'), ('CHEQUE', 'Company Cheque'), ('CASH', 'Cash Disbursement'), ('ONLINE', 'Corporate UPI / Digital')], default='BANK_TRANSFER', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PAID', 'Disbursed / Paid'), ('CANCELLED', 'Cancelled / Reversed')], default='PAID', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='staff.payrollperiod')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Salary Slip',
                'verbose_name_plural': 'Staff Salary Slips',
                'ordering': ['staff_member__employee_id'],
                'unique_together': {('payroll_period', 'staff_member')},
            },
        ),
    ]
