# Generated by Django 6.0.4 on 2026-08-28 17:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('fees', '0001_initial'),
        ('students', '0003_alter_studentenrollment_enrollment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConcession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(help_text='e.g. Sibling Discount (20%), Staff Child (50%)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g. SIBLING_20, STAFF_50, EWS_100, MERIT_25', max_length=30, unique=True)),
                ('concession_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount (%)'), ('FIXED_AMOUNT', 'Fixed Amount Discount (₹)')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or Fixed Rupee amount', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Concession',
                'verbose_name_plural': 'Fee Concessions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feecategory',
            name='category_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fee'), ('LAB', 'Science & Computer Lab Fee'), ('EXAM', 'Examination Fee'), ('ACTIVITY', 'Sports & Co-Curricular Fee'), ('DEVELOPMENT', 'Annual & School Development Charges'), ('LIBRARY', 'Library & Digital Resource Fee'), ('ADMISSION', 'One-Time Admission / Registration Fee'), ('OTHER', 'Other Institutional Charges')], default='TUITION', help_text='Standard accounting head', max_length=30),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='cheque_bank_name',
            field=models.CharField(blank=True, help_text='Issuing Bank & Branch', max_length=100),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque / DD Number', max_length=50),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='upi_utr_number',
            field=models.CharField(blank=True, help_text='12-digit UPI UTR Reference', max_length=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One Time (At Admission)'), ('ANNUAL', 'Annual'), ('QUARTERLY', 'Quarterly (Q1, Q2, Q3, Q4)'), ('MONTHLY', 'Monthly')], default='QUARTERLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfeeinvoice',
            name='title',
            field=models.CharField(help_text='e.g. Q1 Tuition & Science Lab Fee', max_length=150),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash Counter'), ('UPI', 'UPI / QR Code Scan'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / RTGS'), ('CHEQUE', 'Cheque / Demand Draft'), ('ONLINE', 'Online Payment / Parent Portal'), ('CARD', 'Debit / Credit Card (POS)')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Bank UTR or Gateway Transaction Ref', max_length=100),
        ),
        migrations.AddField(
            model_name='studentfeeinvoice',
            name='concession_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_invoices', to='fees.feeconcession'),
        ),
        migrations.CreateModel(
            name='FeeFineRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(default='Standard Late Fee Rule', max_length=100)),
                ('grace_period_days', models.PositiveIntegerField(default=10, help_text='Grace days from issue date before penalty applies')),
                ('fine_type', models.CharField(choices=[('PER_DAY', 'Per Day Overdue (₹/Day)'), ('FLAT', 'Flat Penalty (₹)')], default='PER_DAY', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='₹ per day or flat ₹', max_digits=8)),
                ('max_fine_limit', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_rules', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Fee Fine Rule',
                'verbose_name_plural': 'Fee Fine Rules',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='fees.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='fees.studentfeeinvoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['fee_category__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentConcession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_concessions', to='academics.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_concessions', to=settings.AUTH_USER_MODEL)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='fees.feeconcession')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_concessions', to='students.studentenrollment')),
            ],
            options={
                'verbose_name': 'Student Concession',
                'verbose_name_plural': 'Student Concessions',
                'unique_together': {('student_enrollment', 'concession', 'academic_year')},
            },
        ),
    ]
