# Generated by Django 6.0.4 on 2026-08-26 06:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_phone', models.CharField(max_length=30)),
                ('parent_email', models.EmailField(max_length=254)),
                ('residential_address', models.TextField()),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Application Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('ENTRANCE_SCHEDULED', 'Entrance Exam / Interview Scheduled'), ('ACCEPTED', 'Accepted / Approved'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled as Student')], default='SUBMITTED', max_length=30)),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='academics.academicyear')),
                ('applying_for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='academics.classlevel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-applied_date', '-created_at'],
            },
        ),
    ]
