# Generated by Django 6.0.4 on 2026-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsapplication',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='caste_category',
            field=models.CharField(blank=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='city',
            field=models.CharField(blank=True, default='Kolkata', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='father_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='has_sibling_in_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/photos/%Y/'),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='previous_board',
            field=models.CharField(blank=True, default='CBSE', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='previous_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='sibling_details',
            field=models.CharField(blank=True, help_text='Name, Admission No, and Class of Sibling', max_length=255),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='state',
            field=models.CharField(blank=True, default='West Bengal', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='stream_preference',
            field=models.CharField(blank=True, choices=[('SCIENCE_PCM', 'Science (Physics, Chemistry, Mathematics)'), ('SCIENCE_PCB', 'Science (Physics, Chemistry, Biology)'), ('COMMERCE', 'Commerce with Mathematics / Informatics'), ('HUMANITIES', 'Humanities / Arts & Legal Studies')], max_length=50),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='tc_status',
            field=models.CharField(blank=True, choices=[('ATTACHED', 'Transfer Certificate Attached'), ('WILL_SUBMIT', 'Will Submit Prior to Final Admission'), ('NOT_APPLICABLE', 'Not Applicable (Fresh Admission to Nursery)')], default='WILL_SUBMIT', max_length=50),
        ),
    ]
