# Generated by Django 6.0.4 on 2026-08-29 03:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('documents', '0001_initial'),
        ('staff', '0002_payrollperiod_salarystructure_staffsalaryslip'),
        ('students', '0003_alter_studentenrollment_enrollment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('certificate_type', models.CharField(choices=[('TC', 'Transfer Certificate (TC)'), ('CHARACTER', 'Character Certificate'), ('BONAFIDE', 'Bonafide / Study Certificate'), ('FEE_CLEARANCE', 'Fee Clearance (No Dues) Certificate'), ('MIGRATION', 'Migration Certificate'), ('CUSTOM', 'Special / Custom Certificate')], default='TC', max_length=30)),
                ('header_title', models.CharField(default='TRANSFER CERTIFICATE', max_length=200)),
                ('sub_header', models.CharField(blank=True, default='(Affiliated to CBSE, New Delhi | Affiliation No: 2130894 | School Code: 70123)', max_length=255)),
                ('body_template', models.TextField(blank=True, help_text='HTML or text blueprint for certificate body')),
                ('footer_note', models.TextField(blank=True, default='Certified that the above information is in accordance with the School General Register.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'ordering': ['certificate_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IDCardConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Portrait (Standard 54x86mm Badge)'), ('LANDSCAPE', 'Landscape (Standard 86x54mm Badge)')], default='PORTRAIT', max_length=20)),
                ('theme', models.CharField(choices=[('NAVY_GOLD', 'Academic Navy & Gold (#1E1B4B / #D4AF37)'), ('EMERALD', 'Prestige Emerald (#006C49 / #10B981)'), ('MAROON', 'Royal Maroon (#7E1D1D / #F59E0B)'), ('INDIGO_VIOLET', 'Modern Indigo & Violet (#4F46E5 / #8B5CF6)')], default='NAVY_GOLD', max_length=30)),
                ('primary_color', models.CharField(default='#1E1B4B', max_length=20)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=20)),
                ('show_blood_group', models.BooleanField(default=True)),
                ('show_emergency_contact', models.BooleanField(default=True)),
                ('show_residential_address', models.BooleanField(default=True)),
                ('show_bus_route', models.BooleanField(default=True)),
                ('show_barcode', models.BooleanField(default=True)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('return_policy_text', models.TextField(default='If found, please return to School Administration Office. Apex International Academy, Sector 12, Dwarka, New Delhi. Helpline: +91 11 2659 8000')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ID Card Configuration',
                'verbose_name_plural': 'ID Card Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('certificate_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('book_number', models.CharField(blank=True, default='B-01', max_length=40)),
                ('serial_number', models.CharField(blank=True, default='001', max_length=40)),
                ('verification_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_type', models.CharField(choices=[('TC', 'Transfer Certificate (TC)'), ('CHARACTER', 'Character Certificate'), ('BONAFIDE', 'Bonafide / Study Certificate'), ('FEE_CLEARANCE', 'Fee Clearance (No Dues) Certificate'), ('MIGRATION', 'Migration Certificate'), ('CUSTOM', 'Special / Custom Certificate')], default='TC', max_length=30)),
                ('issue_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('reason_for_leaving', models.CharField(default='Completed Course / Higher Studies', max_length=255)),
                ('general_conduct', models.CharField(default='Good', max_length=100)),
                ('dues_cleared', models.BooleanField(default=True, help_text='Whether all school fee dues have been fully settled')),
                ('total_working_days', models.PositiveIntegerField(default=220)),
                ('total_present_days', models.PositiveIntegerField(default=205)),
                ('last_class_passed', models.CharField(blank=True, max_length=100)),
                ('qualified_for_promotion', models.BooleanField(default=True)),
                ('ncc_cadet_or_scout', models.CharField(blank=True, default='N/A', max_length=100)),
                ('games_played', models.CharField(blank=True, default='Regular participation in school sports', max_length=255)),
                ('custom_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked / Cancelled')], default='ISSUED', max_length=20)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='academics.academicyear')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_school_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='students.student')),
                ('student_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='students.studentenrollment')),
            ],
            options={
                'verbose_name': 'Issued Certificate',
                'verbose_name_plural': 'Issued Certificates',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedIDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('card_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('card_type', models.CharField(choices=[('STUDENT', 'Student ID Card'), ('STAFF', 'Staff & Faculty ID Card')], default='STUDENT', max_length=20)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('barcode_data', models.CharField(blank=True, max_length=100)),
                ('qr_data', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='academics.academicyear')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cards', to='documents.idcardconfiguration')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='staff.staffmember')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students.student')),
            ],
            options={
                'verbose_name': 'Issued ID Card',
                'verbose_name_plural': 'Issued ID Cards',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
