# Generated by Django 6.0.4 on 2026-08-26 06:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In-App Notification',
                'verbose_name_plural': 'In-App Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'All School Personas'), ('TEACHERS', 'Teachers & Faculty Only'), ('STUDENTS', 'Students Only'), ('PARENTS', 'Parents & Guardians Only'), ('STAFF', 'Non-Teaching Staff Only')], default='ALL', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/%Y/%m/')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pins notice to the top of notice board')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField(blank=True, help_text='Optional expiration date', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice Board Announcement',
                'verbose_name_plural': 'Notice Board Announcements',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
