# Generated by Django 6.0.4 on 2026-08-26 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academics.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class_sections', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacherallocation',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectteacherallocation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='academics.section'),
        ),
        migrations.AddField(
            model_name='subjectteacherallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacherallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='staff.staffmember'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_level', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacherallocation',
            unique_together={('academic_year', 'section', 'subject', 'teacher')},
        ),
    ]
