# Generated by Django 6.0.4 on 2026-08-26 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0002_alter_student_city_alter_student_nationality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(default='Standard Letter Grade Scale', max_length=50)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(help_text='e.g. A+, A, B, C, F', max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 4.0, 3.5', max_digits=4)),
                ('description', models.CharField(blank=True, help_text='e.g. Outstanding, Excellent, Fail', max_length=100)),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(help_text='e.g. Term 1 Examinations', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False, help_text='Report cards accessible to parents/students once published')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Exam Term',
                'verbose_name_plural': 'Exam Terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('theory_marks_max', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('practical_marks_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.subject')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.examterm')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'ordering': ['exam_date', 'start_time'],
                'unique_together': {('exam_term', 'class_level', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamMarkEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('theory_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('practical_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_exam_marks', to=settings.AUTH_USER_MODEL)),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.studentenrollment')),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.examschedule')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_entries', to='examinations.gradescale')),
            ],
            options={
                'verbose_name': 'Exam Mark Entry',
                'verbose_name_plural': 'Exam Mark Entries',
                'ordering': ['student_enrollment__roll_number'],
                'unique_together': {('exam_schedule', 'student_enrollment')},
            },
        ),
    ]
