# Generated by Django 6.0.4 on 2026-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammarkentry',
            name='grace_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='exammarkentry',
            name='internal_marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='exammarkentry',
            name='is_medical_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_center',
            field=models.CharField(blank=True, default='Main Academic Campus', max_length=100),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='instructions',
            field=models.TextField(blank=True, default='Carry your Admit Card and institutional ID card. No electronic gadgets permitted.'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='internal_marks_max',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Internal Assessment / Periodic Test / Portfolio', max_digits=5),
        ),
        migrations.AddField(
            model_name='examterm',
            name='admit_card_published',
            field=models.BooleanField(default=True, help_text='Hall tickets available for download/print'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='pass_percentage_threshold',
            field=models.DecimalField(decimal_places=2, default=33.0, help_text='Minimum passing percentage (e.g. 33% / 35%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='examterm',
            name='requires_fee_clearance',
            field=models.BooleanField(default=False, help_text='Require fee clearance up to current term before issuing Admit Cards or publishing results'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='term_type',
            field=models.CharField(choices=[('UNIT_TEST', 'Unit Test / Periodic Assessment'), ('QUARTERLY', 'Quarterly Examination'), ('HALF_YEARLY', 'Term 1 / Half-Yearly'), ('PRE_BOARD', 'Pre-Board Examination'), ('ANNUAL', 'Term 2 / Annual Final Examination')], default='HALF_YEARLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='pass_marks',
            field=models.DecimalField(decimal_places=2, default=33.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='room_number',
            field=models.CharField(blank=True, default='Hall A-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='theory_marks_max',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
    ]
